JC: jarray.h File Reference
jarray.h File Reference
#include <stdarg.h>
#include "jint.h"
Data Structures
struct NDArray
Typedefs
typedef fi64 NDArray_Backer
typedef NDArray_Backer(* NDArray_mapping_t) (NDArray_Backer)
typedef NDArray_Backer(* NDArray_map2ing_t) (NDArray_Backer, NDArray_Backer)
Functions
uptr NDArray_total_size (NDArray *arr)
iptr NDArray_init (NDArray *arr)
Initialise an N-dimensional array.
void NDArray_dest (NDArray *arr)
Clean up an NDArray.
NDArray_Backer NDArray_get (NDArray *arr, uptr index,...)
Get the value in a given cell of an N-dimensional array.
void NDArray_set (NDArray *arr, NDArray_Backer value, uptr index,...)
Set the value in a given cell of an N-dimensional array.
void NDArray_map (NDArray *arr, NDArray_mapping_t mapping)
void NDArray_add (NDArray *arr, NDArray_Backer value)
void NDArray_sub (NDArray *arr, NDArray_Backer value)
void NDArray_mul (NDArray *arr, NDArray_Backer value)
void NDArray_div (NDArray *arr, NDArray_Backer value)
void NDArray_and (NDArray *arr, NDArray_Backer value)
void NDArray_or (NDArray *arr, NDArray_Backer value)
void NDArray_xor (NDArray *arr, NDArray_Backer value)
void NDArray_map2 (NDArray *left, NDArray *right, NDArray_map2ing_t map2ing)
void NDArray_arr_add (NDArray *left, NDArray *right)
void NDArray_arr_sub (NDArray *left, NDArray *right)
void NDArray_arr_mul (NDArray *left, NDArray *right)
void NDArray_arr_div (NDArray *left, NDArray *right)
void NDArray_arr_and (NDArray *left, NDArray *right)
void NDArray_arr_or (NDArray *left, NDArray *right)
void NDArray_arr_xor (NDArray *left, NDArray *right)
Typedef Documentation
NDArray_Backer
typedef fi64 NDArray_Backer
Definition at line 7 of file jarray.h.
NDArray_map2ing_t
typedef NDArray_Backer(* NDArray_map2ing_t) (NDArray_Backer, NDArray_Backer)
Definition at line 16 of file jarray.h.
NDArray_mapping_t
typedef NDArray_Backer(* NDArray_mapping_t) (NDArray_Backer)
Definition at line 15 of file jarray.h.
Function Documentation
NDArray_add()
void NDArray_add (NDArray * arr, NDArray_Backer value)
Definition at line 80 of file jarray.c.
References NDArray::data, and NDArray_total_size().
NDArray_and()
void NDArray_and (NDArray * arr, NDArray_Backer value)
Definition at line 108 of file jarray.c.
References NDArray::data, and NDArray_total_size().
NDArray_arr_add()
void NDArray_arr_add (NDArray * left, NDArray * right)
Definition at line 146 of file jarray.c.
References NDArray::data, NDArray_assert2(), and NDArray_total_size().
NDArray_arr_and()
void NDArray_arr_and (NDArray * left, NDArray * right)
Definition at line 178 of file jarray.c.
References NDArray::data, NDArray_assert2(), and NDArray_total_size().
NDArray_arr_div()
void NDArray_arr_div (NDArray * left, NDArray * right)
Definition at line 170 of file jarray.c.
References NDArray::data, NDArray_assert2(), and NDArray_total_size().
NDArray_arr_mul()
void NDArray_arr_mul (NDArray * left, NDArray * right)
Definition at line 162 of file jarray.c.
References NDArray::data, NDArray_assert2(), and NDArray_total_size().
NDArray_arr_or()
void NDArray_arr_or (NDArray * left, NDArray * right)
Definition at line 186 of file jarray.c.
References NDArray::data, NDArray_assert2(), and NDArray_total_size().
NDArray_arr_sub()
void NDArray_arr_sub (NDArray * left, NDArray * right)
Definition at line 154 of file jarray.c.
References NDArray::data, NDArray_assert2(), and NDArray_total_size().
NDArray_arr_xor()
void NDArray_arr_xor (NDArray * left, NDArray * right)
Definition at line 194 of file jarray.c.
References NDArray::data, NDArray_assert2(), and NDArray_total_size().
NDArray_dest()
void NDArray_dest (NDArray * arr)
Clean up an NDArray.
Parameters
arr The array to finalise.
Definition at line 32 of file jarray.c.
References NDArray::data.
NDArray_div()
void NDArray_div (NDArray * arr, NDArray_Backer value)
Definition at line 101 of file jarray.c.
References NDArray::data, and NDArray_total_size().
NDArray_get()
NDArray_Backer NDArray_get (NDArray * arr, uptr index, ...)
Get the value in a given cell of an N-dimensional array.
Parameters
arr The array to retrieve a value from.
index The index of the value to retrieve.
...
Returns
The value.
Definition at line 42 of file jarray.c.
References NDArray::data, NDArray::dims, and NDArray::size.
NDArray_init()
iptr NDArray_init (NDArray * arr)
Initialise an N-dimensional array.
Parameters
arr The array to initialise.
Returns
On success, 0. On error, -1 and errno is set to indicate the error.
Definition at line 21 of file jarray.c.
References NDArray::data, and NDArray_total_size().
NDArray_map()
void NDArray_map (NDArray * arr, NDArray_mapping_t mapping)
Definition at line 73 of file jarray.c.
References NDArray::data, and NDArray_total_size().
NDArray_map2()
void NDArray_map2 (NDArray * left, NDArray * right, NDArray_map2ing_t map2ing)
Definition at line 138 of file jarray.c.
References NDArray::data, NDArray_assert2(), and NDArray_total_size().
NDArray_mul()
void NDArray_mul (NDArray * arr, NDArray_Backer value)
Definition at line 94 of file jarray.c.
References NDArray::data, and NDArray_total_size().
NDArray_or()
void NDArray_or (NDArray * arr, NDArray_Backer value)
Definition at line 115 of file jarray.c.
References NDArray::data, and NDArray_total_size().
NDArray_set()
void NDArray_set (NDArray * arr, NDArray_Backer value, uptr index, ...)
Set the value in a given cell of an N-dimensional array.
Parameters
arr The array to set a value in.
value The value.
index The index to set the value of.
...
Definition at line 60 of file jarray.c.
References NDArray::data, NDArray::dims, and NDArray::size.
NDArray_sub()
void NDArray_sub (NDArray * arr, NDArray_Backer value)
Definition at line 87 of file jarray.c.
References NDArray::data, and NDArray_total_size().
NDArray_total_size()
uptr NDArray_total_size (NDArray * arr) inline
Definition at line 6 of file jarray.c.
References NDArray::dims, and NDArray::size.
Referenced by NDArray_add(), NDArray_and(), NDArray_arr_add(), NDArray_arr_and(), NDArray_arr_div(), NDArray_arr_mul(), NDArray_arr_or(), NDArray_arr_sub(), NDArray_arr_xor(), NDArray_div(), NDArray_init(), NDArray_map(), NDArray_map2(), NDArray_mul(), NDArray_or(), NDArray_sub(), and NDArray_xor().
NDArray_xor()
void NDArray_xor (NDArray * arr, NDArray_Backer value)
Definition at line 122 of file jarray.c.
References NDArray::data, and NDArray_total_size().