JC: jarray.c File Reference
jarray.c File Reference
#include <assert.h>
#include <memory.h>
#include <stdarg.h>
#include <stdlib.h>
#include "jarray.h"
Functions
uptr NDArray_total_size (NDArray *arr)
iptr NDArray_init (NDArray *arr)
Initialise an N-dimensional array.
void NDArray_dest (NDArray *arr)
Clean up an NDArray.
iptr NDArray_resize (NDArray *arr, uptr **size)
NDArrayBacker * NDArray_ptr (NDArray *arr, uptr index,...)
Get a pointer the the value in a given cell of an N-dimensional array.
NDArrayBacker NDArray_get (NDArray *arr, uptr index,...)
Get the value in a given cell of an N-dimensional array.
void NDArray_set (NDArray *arr, NDArrayBacker value, uptr index,...)
Set the value in a given cell of an N-dimensional array.
void NDArray_map (NDArray *arr, NDArray_mapping_t mapping)
void NDArray_add (NDArray *arr, NDArrayBacker value)
void NDArray_sub (NDArray *arr, NDArrayBacker value)
void NDArray_mul (NDArray *arr, NDArrayBacker value)
void NDArray_div (NDArray *arr, NDArrayBacker value)
void NDArray_and (NDArray *arr, NDArrayBacker value)
void NDArray_or (NDArray *arr, NDArrayBacker value)
void NDArray_xor (NDArray *arr, NDArrayBacker value)
static void NDArray_assert2 (NDArray *left, NDArray *right)
void NDArray_map2 (NDArray *left, NDArray *right, NDArray_map2ing_t map2ing)
void NDArray_arr_add (NDArray *left, NDArray *right)
void NDArray_arr_sub (NDArray *left, NDArray *right)
void NDArray_arr_mul (NDArray *left, NDArray *right)
void NDArray_arr_div (NDArray *left, NDArray *right)
void NDArray_arr_and (NDArray *left, NDArray *right)
void NDArray_arr_or (NDArray *left, NDArray *right)
void NDArray_arr_xor (NDArray *left, NDArray *right)
Function Documentation
NDArray_add()
void NDArray_add (NDArray * arr, NDArrayBacker value)
Definition at line 132 of file jarray.c.
References NDArray::data, and NDArray_total_size().
NDArray_and()
void NDArray_and (NDArray * arr, NDArrayBacker value)
Definition at line 160 of file jarray.c.
References NDArray::data, and NDArray_total_size().
NDArray_arr_add()
void NDArray_arr_add (NDArray * left, NDArray * right)
Definition at line 198 of file jarray.c.
References NDArray::data, NDArray_assert2(), and NDArray_total_size().
NDArray_arr_and()
void NDArray_arr_and (NDArray * left, NDArray * right)
Definition at line 230 of file jarray.c.
References NDArray::data, NDArray_assert2(), and NDArray_total_size().
NDArray_arr_div()
void NDArray_arr_div (NDArray * left, NDArray * right)
Definition at line 222 of file jarray.c.
References NDArray::data, NDArray_assert2(), and NDArray_total_size().
NDArray_arr_mul()
void NDArray_arr_mul (NDArray * left, NDArray * right)
Definition at line 214 of file jarray.c.
References NDArray::data, NDArray_assert2(), and NDArray_total_size().
NDArray_arr_or()
void NDArray_arr_or (NDArray * left, NDArray * right)
Definition at line 238 of file jarray.c.
References NDArray::data, NDArray_assert2(), and NDArray_total_size().
NDArray_arr_sub()
void NDArray_arr_sub (NDArray * left, NDArray * right)
Definition at line 206 of file jarray.c.
References NDArray::data, NDArray_assert2(), and NDArray_total_size().
NDArray_arr_xor()
void NDArray_arr_xor (NDArray * left, NDArray * right)
Definition at line 246 of file jarray.c.
References NDArray::data, NDArray_assert2(), and NDArray_total_size().
NDArray_assert2()
static void NDArray_assert2 (NDArray * left, NDArray * right) static
Definition at line 181 of file jarray.c.
References NDArray::dims, and NDArray::size.
Referenced by NDArray_arr_add(), NDArray_arr_and(), NDArray_arr_div(), NDArray_arr_mul(), NDArray_arr_or(), NDArray_arr_sub(), NDArray_arr_xor(), and NDArray_map2().
NDArray_dest()
void NDArray_dest (NDArray * arr)
Clean up an NDArray.
Parameters
arr The array to finalise.
Definition at line 33 of file jarray.c.
References NDArray::data.
NDArray_div()
void NDArray_div (NDArray * arr, NDArrayBacker value)
Definition at line 153 of file jarray.c.
References NDArray::data, and NDArray_total_size().
NDArray_get()
NDArrayBacker NDArray_get (NDArray * arr, uptr index, ...)
Get the value in a given cell of an N-dimensional array.
Parameters
arr The array to retrieve a value from.
index The index of the value to retrieve.
...
Returns
The value.
Definition at line 94 of file jarray.c.
References NDArray::data, NDArray::dims, and NDArray::size.
NDArray_init()
iptr NDArray_init (NDArray * arr)
Initialise an N-dimensional array.
Parameters
arr The array to initialise.
Returns
On success, 0. On error, -1 and errno is set to indicate the error.
Definition at line 22 of file jarray.c.
References NDArray::data, and NDArray_total_size().
NDArray_map()
void NDArray_map (NDArray * arr, NDArray_mapping_t mapping)
Definition at line 125 of file jarray.c.
References NDArray::data, and NDArray_total_size().
NDArray_map2()
void NDArray_map2 (NDArray * left, NDArray * right, NDArray_map2ing_t map2ing)
Definition at line 190 of file jarray.c.
References NDArray::data, NDArray_assert2(), and NDArray_total_size().
NDArray_mul()
void NDArray_mul (NDArray * arr, NDArrayBacker value)
Definition at line 146 of file jarray.c.
References NDArray::data, and NDArray_total_size().
NDArray_or()
void NDArray_or (NDArray * arr, NDArrayBacker value)
Definition at line 167 of file jarray.c.
References NDArray::data, and NDArray_total_size().
NDArray_ptr()
NDArrayBacker* NDArray_ptr (NDArray * arr, uptr index, ...)
Get a pointer the the value in a given cell of an N-dimensional array.
Parameters
arr The array to retrieve a pointer from.
index The index of the value to retrieve a pointer to.
...
Returns
A pointer to that value.
Definition at line 76 of file jarray.c.
References NDArray::data, NDArray::dims, and NDArray::size.
NDArray_resize()
iptr NDArray_resize (NDArray * arr, uptr ** size)
Definition at line 38 of file jarray.c.
References NDArray::data, NDArray::dims, NDArray_total_size(), and NDArray::size.
NDArray_set()
void NDArray_set (NDArray * arr, NDArrayBacker value, uptr index, ...)
Set the value in a given cell of an N-dimensional array.
Parameters
arr The array to set a value in.
value The value.
index The index to set the value of.
...
Definition at line 112 of file jarray.c.
References NDArray::data, NDArray::dims, and NDArray::size.
NDArray_sub()
void NDArray_sub (NDArray * arr, NDArrayBacker value)
Definition at line 139 of file jarray.c.
References NDArray::data, and NDArray_total_size().
NDArray_total_size()
uptr NDArray_total_size (NDArray * arr) inline
Definition at line 7 of file jarray.c.
References NDArray::dims, and NDArray::size.
Referenced by NDArray_add(), NDArray_and(), NDArray_arr_add(), NDArray_arr_and(), NDArray_arr_div(), NDArray_arr_mul(), NDArray_arr_or(), NDArray_arr_sub(), NDArray_arr_xor(), NDArray_div(), NDArray_init(), NDArray_map(), NDArray_map2(), NDArray_mul(), NDArray_or(), NDArray_resize(), NDArray_sub(), and NDArray_xor().
NDArray_xor()
void NDArray_xor (NDArray * arr, NDArrayBacker value)
Definition at line 174 of file jarray.c.
References NDArray::data, and NDArray_total_size().