JC: jbits.h File Reference
jbits.h File Reference
#include "jint.h"
Data Structures
struct BitArray
struct BitArray2d
Macros
#define popcount(x)
#define pop0count(x)
Typedefs
typedef fu8 BitArrayBacker
typedef uptr BitArray2dBacker
Functions
uptr popcount8 (u8 x)
uptr popcount16 (u16 x)
uptr popcount32 (u32 x)
uptr popcount64 (u64 x)
uptr pop0count8 (u8 x)
uptr pop0count16 (u16 x)
uptr pop0count32 (u32 x)
uptr pop0count64 (u64 x)
static uptr BitArray_offset (uptr index)
iptr BitArray_init (BitArray *arr)
void BitArray_dest (BitArray *arr)
uptr BitArray_get (BitArray *arr, uptr index)
void BitArray_set (BitArray *arr, uptr index, BitArrayBacker value)
void BitArray_on (BitArray *arr, uptr index)
void BitArray_off (BitArray *arr, uptr index)
void BitArray_toggle (BitArray *arr, uptr index)
void BitArray_flip (BitArray *arr)
void BitArray_and (BitArray *left, BitArray *right)
uptr BitArray_popcount (BitArray *arr)
static uptr BitArray2d_row_width (BitArray2d *arr)
static uptr BitArray2d_offset (uptr col)
iptr BitArray2d_init (BitArray2d *arr)
Initialise a BitArray2d struct.
void BitArray2d_dest (BitArray2d *arr)
Handle cleaning up a BitArray2d.
uptr BitArray2d_get (BitArray2d *arr, uptr row, uptr col)
Get the value in a given cell of a BitArray2d.
void BitArray2d_set (BitArray2d *arr, uptr row, uptr col, BitArray2dBacker value)
Set the value in a given cell of a BitArray2d.
void BitArray2d_on (BitArray2d *arr, uptr row, uptr col)
Set the value in a given cell of a BitArray2d to 1.
void BitArray2d_off (BitArray2d *arr, uptr row, uptr col)
Set the value in a given cell of a BitArray2d to 0.
void BitArray2d_toggle (BitArray2d *arr, uptr row, uptr col)
Toggle value in a given cell of a BitArray2d.
uptr BitArray2d_count_on (BitArray2d *arr)
uptr BitArray2d_count_off (BitArray2d *arr)
void BitArray2d_flip (BitArray2d *arr)
Variables
static const uptr BitArray_BACKER_BITS = (sizeof(BitArrayBacker) * 8)
static const uptr BitArray2d_BACKER_BITS = (sizeof(BitArray2dBacker) * 8)
Macro Definition Documentation
pop0count
#define pop0count (x)
Value:
_Generic((x),      \
u8 : pop0count8,                        \
u16: pop0count16,                       \
u32: pop0count32,                       \
u64: pop0count64)                       \
(x)
Definition at line 23 of file jbits.h.
popcount
#define popcount (x)
Value:
_Generic((x),      \
u8 : popcount8,                        \
u16: popcount16,                       \
u32: popcount32,                       \
u64: popcount64)                       \
(x)
Definition at line 11 of file jbits.h.
Typedef Documentation
BitArray2dBacker
typedef uptr BitArray2dBacker
Definition at line 54 of file jbits.h.
BitArrayBacker
typedef fu8 BitArrayBacker
Definition at line 30 of file jbits.h.
Function Documentation
BitArray2d_count_off()
uptr BitArray2d_count_off (BitArray2d * arr)
Definition at line 232 of file jbits.c.
References BitArray2d_BACKER_BITS, BitArray2d_get(), BitArray2d_row_width(), BitArray2d::cols, pop0count, BitArray2d::row_starts, and BitArray2d::rows.
BitArray2d_count_on()
uptr BitArray2d_count_on (BitArray2d * arr)
Definition at line 213 of file jbits.c.
References BitArray2d_BACKER_BITS, BitArray2d_get(), BitArray2d_row_width(), BitArray2d::cols, popcount, BitArray2d::row_starts, and BitArray2d::rows.
BitArray2d_dest()
void BitArray2d_dest (BitArray2d * arr)
Handle cleaning up a BitArray2d.
Parameters
arr The BitArray2d to clean up (by pointer).
Definition at line 146 of file jbits.c.
References BitArray2d::data, and BitArray2d::row_starts.
BitArray2d_flip()
void BitArray2d_flip (BitArray2d * arr)
Definition at line 251 of file jbits.c.
References BitArray2d_BACKER_BITS, BitArray2d_off(), BitArray2d_row_width(), BitArray2d::cols, BitArray2d::row_starts, and BitArray2d::rows.
BitArray2d_get()
uptr BitArray2d_get (BitArray2d * arr, uptr row, uptr col)
Get the value in a given cell of a BitArray2d.
Parameters
arr The BitArray2d to retrieve a bit from.
row The row index (0-based) to retrieve the bit from.
col The column index (0-based) to retrieve the bit from.
Returns
0 or 1.
Definition at line 157 of file jbits.c.
References BitArray2d_offset(), BitArray2d_row_width(), and BitArray2d::row_starts.
Referenced by BitArray2d_count_off(), and BitArray2d_count_on().
BitArray2d_init()
iptr BitArray2d_init (BitArray2d * arr)
Initialise a BitArray2d struct.
This function allocates two arrays - one to store row_starts, which contains pointers to the start of each row, and data, which contains each row.
Parameters
arr The array to initialise.
Returns
On success, 0. On error, -1, and errno is set to indicate the error.
Definition at line 122 of file jbits.c.
References BitArray2d_row_width(), BitArray2d::cols, BitArray2d::data, BitArray2d::row_starts, and BitArray2d::rows.
BitArray2d_off()
void BitArray2d_off (BitArray2d * arr, uptr row, uptr col)
Set the value in a given cell of a BitArray2d to 0.
Parameters
arr The BitArray2d to set a bit in.
row The row index (0-based) of the bit to set.
col The column index (0-based) of the bit to set.
Definition at line 194 of file jbits.c.
References BitArray2d_offset(), BitArray2d_row_width(), and BitArray2d::row_starts.
Referenced by BitArray2d_flip().
BitArray2d_offset()
static uptr BitArray2d_offset (uptr col) inline static
Definition at line 68 of file jbits.h.
References BitArray2d_BACKER_BITS.
Referenced by BitArray2d_get(), BitArray2d_off(), BitArray2d_on(), BitArray2d_set(), and BitArray2d_toggle().
BitArray2d_on()
void BitArray2d_on (BitArray2d * arr, uptr row, uptr col)
Set the value in a given cell of a BitArray2d to 1.
Parameters
arr The BitArray2d to set a bit in.
row The row index (0-based) of the bit to set.
col The column index (0-based) of the bit to set.
Definition at line 184 of file jbits.c.
References BitArray2d_offset(), BitArray2d_row_width(), and BitArray2d::row_starts.
BitArray2d_row_width()
static uptr BitArray2d_row_width (BitArray2d * arr) inline static
Definition at line 64 of file jbits.h.
References BitArray2d_BACKER_BITS, and BitArray2d::cols.
Referenced by BitArray2d_count_off(), BitArray2d_count_on(), BitArray2d_flip(), BitArray2d_get(), BitArray2d_init(), BitArray2d_off(), BitArray2d_on(), BitArray2d_set(), and BitArray2d_toggle().
BitArray2d_set()
void BitArray2d_set (BitArray2d * arr, uptr row, uptr col, uptr value)
Set the value in a given cell of a BitArray2d.
Parameters
arr The BitArray2d to set a bit in.
row The row index (0-based) of the bit to set.
col The column index (0-based) of the bit to set.
value The value to set at the given coordinates, 0 or 1.
Definition at line 170 of file jbits.c.
References BitArray2d_offset(), BitArray2d_row_width(), and BitArray2d::row_starts.
BitArray2d_toggle()
void BitArray2d_toggle (BitArray2d * arr, uptr row, uptr col)
Toggle value in a given cell of a BitArray2d.
Cells with a 0 in them will be set to 1, and cells with a 1 in them will be set to 0.
Parameters
arr The BitArray2d to set a bit in.
row The row index (0-based) of the bit to set.
col The column index (0-based) of the bit to set.
Definition at line 207 of file jbits.c.
References BitArray2d_offset(), BitArray2d_row_width(), and BitArray2d::row_starts.
BitArray_and()
void BitArray_and (BitArray * left, BitArray * right)
Definition at line 101 of file jbits.c.
References BitArray_BACKER_BITS, BitArray::data, and BitArray::length.
BitArray_dest()
void BitArray_dest (BitArray * arr)
Definition at line 61 of file jbits.c.
References BitArray::data.
BitArray_flip()
void BitArray_flip (BitArray * arr)
Definition at line 93 of file jbits.c.
References BitArray_BACKER_BITS, BitArray::data, and BitArray::length.
BitArray_get()
uptr BitArray_get (BitArray * arr, uptr index)
Definition at line 65 of file jbits.c.
References BitArray_BACKER_BITS, BitArray_offset(), and BitArray::data.
BitArray_init()
iptr BitArray_init (BitArray * arr)
Definition at line 52 of file jbits.c.
References BitArray_BACKER_BITS, BitArray::data, and BitArray::length.
BitArray_off()
void BitArray_off (BitArray * arr, uptr index)
Definition at line 83 of file jbits.c.
References BitArray_BACKER_BITS, BitArray_offset(), and BitArray::data.
BitArray_offset()
static uptr BitArray_offset (uptr index) inline static
Definition at line 39 of file jbits.h.
References BitArray_BACKER_BITS.
Referenced by BitArray_get(), BitArray_off(), BitArray_on(), BitArray_set(), and BitArray_toggle().
BitArray_on()
void BitArray_on (BitArray * arr, uptr index)
Definition at line 78 of file jbits.c.
References BitArray_BACKER_BITS, BitArray_offset(), and BitArray::data.
BitArray_popcount()
uptr BitArray_popcount (BitArray * arr)
Definition at line 108 of file jbits.c.
References BitArray_BACKER_BITS, BitArray::data, BitArray::length, and popcount.
BitArray_set()
void BitArray_set (BitArray * arr, uptr index, BitArrayBacker value)
Definition at line 70 of file jbits.c.
References BitArray_BACKER_BITS, BitArray_offset(), and BitArray::data.
BitArray_toggle()
void BitArray_toggle (BitArray * arr, uptr index)
Definition at line 88 of file jbits.c.
References BitArray_BACKER_BITS, BitArray_offset(), and BitArray::data.
pop0count16()
uptr pop0count16 (u16 x)
Definition at line 40 of file jbits.c.
References pop0count_body.
pop0count32()
uptr pop0count32 (u32 x)
Definition at line 44 of file jbits.c.
References pop0count_body.
pop0count64()
uptr pop0count64 (u64 x)
Definition at line 48 of file jbits.c.
References pop0count_body.
pop0count8()
uptr pop0count8 (u8 x)
Definition at line 36 of file jbits.c.
References pop0count_body.
popcount16()
uptr popcount16 (u16 x)
Definition at line 24 of file jbits.c.
References popcount_body.
popcount32()
uptr popcount32 (u32 x)
Definition at line 28 of file jbits.c.
References popcount_body.
popcount64()
uptr popcount64 (u64 x)
Definition at line 32 of file jbits.c.
References popcount_body.
popcount8()
uptr popcount8 (u8 x)
Definition at line 20 of file jbits.c.
References popcount_body.
Variable Documentation
BitArray2d_BACKER_BITS
const uptr BitArray2d_BACKER_BITS = (sizeof(BitArray2dBacker) * 8) static
Definition at line 62 of file jbits.h.
Referenced by BitArray2d_count_off(), BitArray2d_count_on(), BitArray2d_flip(), BitArray2d_offset(), and BitArray2d_row_width().
BitArray_BACKER_BITS
const uptr BitArray_BACKER_BITS = (sizeof(BitArrayBacker) * 8) static
Definition at line 32 of file jbits.h.
Referenced by BitArray_and(), BitArray_flip(), BitArray_get(), BitArray_init(), BitArray_off(), BitArray_offset(), BitArray_on(), BitArray_popcount(), BitArray_set(), and BitArray_toggle().