JC: jiterator.h File Reference
jiterator.h File Reference
#include <stdbool.h>
#include "jvector.h"
Data Structures
struct jiterator
A struct that exposes two functions to allow iteration of elements, one at a time.
struct pair
Typedefs
typedef bool jiterator_next(jiterator *self)
typedef void * jiterator_map_fn(void *element)
typedef void * jiterator_map2_fn(void *a, void *b)
typedef void jiterator_action_fn(void *element)
typedef bool jiterator_predicate_fn(void *element)
typedef void * jiterator_reduce_fn(void *acc, void *elt)
typedef void * jiterator_fold_fn(void *acc, void *elt)
typedef int jiterator_compare_fn(void *a, void *b)
typedef void * jiterator_generator_fn(void)
Functions
void jiterator_collect (jiterator *source, Vector *vec)
void jiterator_alloc_dest (jiterator *self)
void jiterator_vector_reset (jiterator *self)
void jiterator_vector_init (jiterator *self, Vector *vec)
void jiterator_map_init (jiterator *self, jiterator *source, jiterator_map_fn *map)
void jiterator_action_init (jiterator *self, jiterator *source, jiterator_action_fn *action)
void jiterator_filter_init (jiterator *self, jiterator *source, jiterator_predicate_fn *filter)
bool jiterator_reduce (jiterator *source, jiterator_reduce_fn *reduce, void **result)
void * jiterator_fold (jiterator *source, jiterator_fold_fn *fold, void *initial)
void jiterator_scan_init (jiterator *self, jiterator *source, jiterator_fold_fn *scan, void *initial)
bool jiterator_min_max (jiterator *source, jiterator_compare_fn *compare, pair *result)
bool jiterator_min (jiterator *source, jiterator_compare_fn *compare, void **result)
bool jiterator_max (jiterator *source, jiterator_compare_fn *compare, void **result)
bool jiterator_all (jiterator *source, jiterator_predicate_fn *predicate)
bool jiterator_any (jiterator *source, jiterator_predicate_fn *predicate)
void jiterator_iota_init (jiterator *self, iptr start, iptr step)
void jiterator_take_init (jiterator *self, jiterator *source, uptr count)
void jiterator_drop_init (jiterator *self, jiterator *source, uptr count)
void jiterator_take_while_init (jiterator *self, jiterator *source, jiterator_predicate_fn *filter)
void jiterator_drop_while_init (jiterator *self, jiterator *source, jiterator_predicate_fn *filter)
void jiterator_zip_init (jiterator *self, jiterator *source1, jiterator *source2)
void jiterator_enumerate_init (jiterator *self, jiterator *source)
void jiterator_pairwise_init (jiterator *self, jiterator *source)
void jiterator_once_init (jiterator *self, void *value)
void jiterator_once_with_init (jiterator *self, jiterator_generator_fn *action)
void jiterator_repeat_init (jiterator *self, void *action)
void jiterator_repeat_with_init (jiterator *self, jiterator_generator_fn *action)
void jiterator_concat_init (jiterator *self, jiterator *source1, jiterator *source2)
Typedef Documentation
jiterator_action_fn
typedef void jiterator_action_fn(void *element)
Definition at line 37 of file jiterator.h.
jiterator_compare_fn
typedef int jiterator_compare_fn(void *a, void *b)
Definition at line 50 of file jiterator.h.
jiterator_fold_fn
typedef void* jiterator_fold_fn(void *acc, void *elt)
Definition at line 46 of file jiterator.h.
jiterator_generator_fn
typedef void* jiterator_generator_fn(void)
Definition at line 66 of file jiterator.h.
jiterator_map2_fn
typedef void* jiterator_map2_fn(void *a, void *b)
Definition at line 34 of file jiterator.h.
jiterator_map_fn
typedef void* jiterator_map_fn(void *element)
Definition at line 33 of file jiterator.h.
jiterator_next
typedef bool jiterator_next(jiterator *self)
Definition at line 9 of file jiterator.h.
jiterator_predicate_fn
typedef bool jiterator_predicate_fn(void *element)
Definition at line 40 of file jiterator.h.
jiterator_reduce_fn
typedef void* jiterator_reduce_fn(void *acc, void *elt)
Definition at line 43 of file jiterator.h.
Function Documentation
jiterator_action_init()
void jiterator_action_init (jiterator * self, jiterator * source, jiterator_action_fn * action)
Definition at line 114 of file jiterator.c.
References action, and jiterator_action_next().
jiterator_all()
bool jiterator_all (jiterator * source, jiterator_predicate_fn * predicate)
Definition at line 232 of file jiterator.c.
References jiterator::current, and jiterator::next.
jiterator_alloc_dest()
void jiterator_alloc_dest (jiterator * self)
Definition at line 32 of file jiterator.c.
jiterator_any()
bool jiterator_any (jiterator * source, jiterator_predicate_fn * predicate)
Definition at line 241 of file jiterator.c.
References jiterator::current, and jiterator::next.
jiterator_collect()
void jiterator_collect (jiterator * source, Vector * vec)
Definition at line 23 of file jiterator.c.
References jiterator::current, Vector::data, Vector::length, jiterator::next, Vector_default(), and Vector_grow_if_full().
jiterator_concat_init()
void jiterator_concat_init (jiterator * self, jiterator * source1, jiterator * source2)
Definition at line 588 of file jiterator.c.
References jiterator::current, and jiterator_concat_next().
jiterator_drop_init()
void jiterator_drop_init (jiterator * self, jiterator * source, uptr count)
Definition at line 323 of file jiterator.c.
References jiterator::current, and jiterator_drop_next().
jiterator_drop_while_init()
void jiterator_drop_while_init (jiterator * self, jiterator * source, jiterator_predicate_fn * filter)
Definition at line 388 of file jiterator.c.
References filter, jiterator_drop_while_next(), and jiterator::next.
jiterator_enumerate_init()
void jiterator_enumerate_init (jiterator * self, jiterator * source)
Definition at line 452 of file jiterator.c.
References jiterator::current, and jiterator_enumerate_next().
jiterator_filter_init()
void jiterator_filter_init (jiterator * self, jiterator * source, jiterator_predicate_fn * filter)
Definition at line 142 of file jiterator.c.
References filter, filter_iterator_next(), and jiterator::next.
jiterator_fold()
void* jiterator_fold (jiterator * source, jiterator_fold_fn * fold, void * initial)
Definition at line 161 of file jiterator.c.
References jiterator::current, fold, and jiterator::next.
jiterator_iota_init()
void jiterator_iota_init (jiterator * self, iptr start, iptr step)
Definition at line 266 of file jiterator.c.
References jiterator_iota_next().
jiterator_map_init()
void jiterator_map_init (jiterator * self, jiterator * source, jiterator_map_fn * map)
Definition at line 89 of file jiterator.c.
References map, map_iterator_next(), and jiterator::next.
jiterator_max()
bool jiterator_max (jiterator * source, jiterator_compare_fn * compare, void ** result)
Definition at line 222 of file jiterator.c.
References jiterator_min_max(), and pair::second.
jiterator_min()
bool jiterator_min (jiterator * source, jiterator_compare_fn * compare, void ** result)
Definition at line 212 of file jiterator.c.
References pair::first, and jiterator_min_max().
jiterator_min_max()
bool jiterator_min_max (jiterator * source, jiterator_compare_fn * compare, pair * result)
Definition at line 195 of file jiterator.c.
References jiterator::current, pair::first, jiterator::next, and pair::second.
Referenced by jiterator_max(), and jiterator_min().
jiterator_once_init()
void jiterator_once_init (jiterator * self, void * value)
Definition at line 513 of file jiterator.c.
References jiterator_once_next().
jiterator_once_with_init()
void jiterator_once_with_init (jiterator * self, jiterator_generator_fn * action)
Definition at line 537 of file jiterator.c.
References action, and jiterator_once_with_next().
jiterator_pairwise_init()
void jiterator_pairwise_init (jiterator * self, jiterator * source)
Definition at line 488 of file jiterator.c.
References jiterator::current, and jiterator_pairwise_next().
jiterator_reduce()
bool jiterator_reduce (jiterator * source, jiterator_reduce_fn * reduce, void ** result)
Definition at line 150 of file jiterator.c.
References jiterator::current, jiterator::next, and reduce.
jiterator_repeat_init()
void jiterator_repeat_init (jiterator * self, void * action)
Definition at line 551 of file jiterator.c.
References jiterator_repeat_next().
jiterator_repeat_with_init()
void jiterator_repeat_with_init (jiterator * self, jiterator_generator_fn * action)
Definition at line 564 of file jiterator.c.
References action, and jiterator_repeat_with_next().
jiterator_scan_init()
void jiterator_scan_init (jiterator * self, jiterator * source, jiterator_fold_fn * scan, void * initial)
Definition at line 186 of file jiterator.c.
References jiterator_scan_next(), jiterator::next, and scan.
jiterator_take_init()
void jiterator_take_init (jiterator * self, jiterator * source, uptr count)
Definition at line 294 of file jiterator.c.
References jiterator::current, and jiterator_take_next().
jiterator_take_while_init()
void jiterator_take_while_init (jiterator * self, jiterator * source, jiterator_predicate_fn * filter)
Definition at line 354 of file jiterator.c.
References filter, jiterator_take_while_next(), and jiterator::next.
jiterator_vector_init()
void jiterator_vector_init (jiterator * self, Vector * vec)
Definition at line 65 of file jiterator.c.
References jiterator_vector_next().
jiterator_vector_reset()
void jiterator_vector_reset (jiterator * self)
Definition at line 59 of file jiterator.c.
jiterator_zip_init()
void jiterator_zip_init (jiterator * self, jiterator * source1, jiterator * source2)
Definition at line 417 of file jiterator.c.
References jiterator::current, and jiterator_zip_next().