JC: jlog.c File Reference
jlog.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <time.h>
#include <string.h>
#include "jlog.h"
#include "jvector.h"
Macros
#define jlogger_log_level_impl(name, level)
Functions
const char * jlog_level_to_string (jlog_level level)
jlogger_t jlogger_new ()
void jlogger_free (jlogger_t self)
void jlogger_add_sink (jlogger_t self, jlogger_sink_t sink)
static bool jlogger_vlog (jlogger_t self, jlog_level level, const char *fmt, va_list args)
bool jlogger_log (jlogger_t self, jlog_level level, const char *fmt,...)
jlogger_log_level_impl (trace, JLOG_LEVEL_TRACE)
bool jlogger_stdout_sink (__attribute__((unused)) jlogger_sink_t self, jlog_level level, const char *fmt,...)
void jlogger_stdout_sink_new (jlogger_sink_t sink)
bool jlogger_stderr_sink (__attribute__((unused)) jlogger_sink_t self, jlog_level level, const char *fmt,...)
void jlogger_stderr_sink_new (jlogger_sink_t sink)
bool jlogger_std_hybrid_sink (__attribute__((unused)) jlogger_sink_t self, jlog_level level, const char *fmt,...)
void jlogger_std_hybrid_sink_new (jlogger_sink_t sink)
void jlogger_sink_add_filter (jlogger_sink_t self, jlogger_sink_filter *filter)
bool jlogger_file_sink (jlogger_sink_t self, jlog_level level, const char *fmt,...)
void jlogger_file_sink_free (jlogger_sink_t self)
void jlogger_file_sink_new (jlogger_sink_t sink, char *path)
Create a new file sink.
bool jlogger_rotating_file_sink_rotate (jlogger_rotating_file_sink_data_s *data)
bool jlogger_rotating_file_sink_maybe_rotate (jlogger_rotating_file_sink_data_s *data)
bool jlogger_rotating_file_sink (jlogger_sink_t sink, jlog_level level, const char *fmt,...)
void jloggger_rotating_file_sink_free (jlogger_sink_t self)
void jlogger_rotating_file_sink_new (jlogger_sink_t sink, char *path_template, uptr path_template_len, u32 max_size, double max_age)
Macro Definition Documentation
jlogger_log_level_impl
#define jlogger_log_level_impl (name, level)
Value:
    bool jlogger_log_##name(jlogger_t self, const char *fmt, ...) { \
        va_list args; \
        va_start(args, fmt); \
        bool result = jlogger_vlog(self, level, fmt, args); \
        va_end(args); \
        return result; \
    }
Definition at line 71 of file jlog.c.
Function Documentation
jlog_level_to_string()
const char* jlog_level_to_string (jlog_level level)
Definition at line 8 of file jlog.c.
References JLOG_LEVEL_DEBUG, JLOG_LEVEL_ERROR, JLOG_LEVEL_FATAL, JLOG_LEVEL_INFO, JLOG_LEVEL_TRACE, and JLOG_LEVEL_WARN.
Referenced by jlogger_log_level_impl().
jlogger_add_sink()
void jlogger_add_sink (jlogger_t self, jlogger_sink_t sink)
Definition at line 45 of file jlog.c.
References Vector_push_back().
jlogger_file_sink()
bool jlogger_file_sink (jlogger_sink_t self, jlog_level level, const char * fmt, ...)
Definition at line 154 of file jlog.c.
Referenced by jlogger_file_sink_new().
jlogger_file_sink_free()
void jlogger_file_sink_free (jlogger_sink_t self)
Definition at line 163 of file jlog.c.
Referenced by jlogger_file_sink_new().
jlogger_file_sink_new()
void jlogger_file_sink_new (jlogger_sink_t sink, char * path)
Create a new file sink.
Parameters
sink The sink to initialise.
path A path to the file to log to. Ownership is transferred to the sink.
Definition at line 174 of file jlog.c.
References jlogger_file_sink(), jlogger_file_sink_free(), and Vector_default().
jlogger_free()
void jlogger_free (jlogger_t self)
Definition at line 36 of file jlog.c.
References Vector_dest().
jlogger_log()
bool jlogger_log (jlogger_t self, jlog_level level, const char * fmt, ...)
Definition at line 63 of file jlog.c.
References jlogger_vlog().
jlogger_log_level_impl()
jlogger_log_level_impl (trace , JLOG_LEVEL_TRACE)
Definition at line 80 of file jlog.c.
References jlog_level_to_string().
jlogger_new()
jlogger_t jlogger_new ()
Definition at line 27 of file jlog.c.
References Vector_init().
jlogger_rotating_file_sink()
bool jlogger_rotating_file_sink (jlogger_sink_t sink, jlog_level level, const char * fmt, ...)
Definition at line 278 of file jlog.c.
References jlogger_rotating_file_sink_maybe_rotate().
Referenced by jlogger_rotating_file_sink_new().
jlogger_rotating_file_sink_maybe_rotate()
bool jlogger_rotating_file_sink_maybe_rotate (jlogger_rotating_file_sink_data_s * data)
Definition at line 247 of file jlog.c.
References jlogger_rotating_file_sink_rotate().
Referenced by jlogger_rotating_file_sink().
jlogger_rotating_file_sink_new()
void jlogger_rotating_file_sink_new (jlogger_sink_t sink, char * path_template, uptr path_template_len, u32 max_size, double max_age)
Definition at line 302 of file jlog.c.
References jlogger_rotating_file_sink(), jloggger_rotating_file_sink_free(), and Vector_default().
jlogger_rotating_file_sink_rotate()
bool jlogger_rotating_file_sink_rotate (jlogger_rotating_file_sink_data_s * data)
Definition at line 195 of file jlog.c.
Referenced by jlogger_rotating_file_sink_maybe_rotate().
jlogger_sink_add_filter()
void jlogger_sink_add_filter (jlogger_sink_t self, jlogger_sink_filter * filter)
Definition at line 145 of file jlog.c.
References filter, and Vector_push_back().
jlogger_std_hybrid_sink()
bool jlogger_std_hybrid_sink (__attribute__((unused)) jlogger_sink_t self, jlog_level level, const char * fmt, ...)
Definition at line 130 of file jlog.c.
References JLOG_LEVEL_WARN.
Referenced by jlogger_std_hybrid_sink_new().
jlogger_std_hybrid_sink_new()
void jlogger_std_hybrid_sink_new (jlogger_sink_t sink)
Definition at line 140 of file jlog.c.
References jlogger_std_hybrid_sink(), and Vector_default().
jlogger_stderr_sink()
bool jlogger_stderr_sink (__attribute__((unused)) jlogger_sink_t self, jlog_level level, const char * fmt, ...)
Definition at line 117 of file jlog.c.
Referenced by jlogger_stderr_sink_new().
jlogger_stderr_sink_new()
void jlogger_stderr_sink_new (jlogger_sink_t sink)
Definition at line 125 of file jlog.c.
References jlogger_stderr_sink(), and Vector_default().
jlogger_stdout_sink()
bool jlogger_stdout_sink (__attribute__((unused)) jlogger_sink_t self, jlog_level level, const char * fmt, ...)
Definition at line 104 of file jlog.c.
Referenced by jlogger_stdout_sink_new().
jlogger_stdout_sink_new()
void jlogger_stdout_sink_new (jlogger_sink_t sink)
Definition at line 112 of file jlog.c.
References jlogger_stdout_sink(), and Vector_default().
jlogger_vlog()
static bool jlogger_vlog (jlogger_t self, jlog_level level, const char * fmt, va_list args) static
Definition at line 49 of file jlog.c.
References filter.
Referenced by jlogger_log().
jloggger_rotating_file_sink_free()
void jloggger_rotating_file_sink_free (jlogger_sink_t self)
Definition at line 295 of file jlog.c.
Referenced by jlogger_rotating_file_sink_new().