JC: jlog.h File Reference
jlog.h File Reference
#include <stdbool.h>
#include "jvector.h"
Data Structures
struct jlogger_s
struct jlogger_sink_s
Typedefs
typedef jlogger_s * jlogger_t
typedef jlogger_sink_s * jlogger_sink_t
typedef void jlogger_sink_free_fn(jlogger_sink_t self)
typedef bool jlogger_sink_fn(jlogger_sink_t self, jlog_level level, const char *fmt,...)
typedef bool jlogger_sink_filter(jlogger_sink_t self, jlog_level level, const char *fmt, va_list args)
Enumerations
enum jlog_level {
JLOG_LEVEL_TRACE ,
JLOG_LEVEL_DEBUG ,
JLOG_LEVEL_INFO ,
JLOG_LEVEL_WARN ,
JLOG_LEVEL_ERROR ,
JLOG_LEVEL_FATAL
}
Functions
const char * jlog_level_to_string (jlog_level level)
void jlogger_sink_add_filter (jlogger_sink_t self, jlogger_sink_filter *filter)
jlogger_t jlogger_new ()
void jlogger_free (jlogger_t self)
void jlogger_add_sink (jlogger_t self, jlogger_sink_t sink)
bool jlogger_log (jlogger_t self, jlog_level level, const char *fmt,...)
bool jlogger_log_trace (jlogger_t self, const char *fmt,...)
bool jlogger_log_debug (jlogger_t self, const char *fmt,...)
bool jlogger_log_info (jlogger_t self, const char *fmt,...)
bool jlogger_log_warn (jlogger_t self, const char *fmt,...)
bool jlogger_log_error (jlogger_t self, const char *fmt,...)
bool jlogger_log_fatal (jlogger_t self, const char *fmt,...)
void jlogger_stdout_sink_new (jlogger_sink_t sink)
void jlogger_stderr_sink_new (jlogger_sink_t sink)
void jlogger_std_hybrid_sink_new (jlogger_sink_t sink)
void jlogger_file_sink_new (jlogger_sink_t sink, char *path)
Create a new file sink.
void jlogger_rotating_file_sink_new (jlogger_sink_t sink, char *path_template, uptr path_template_len, u32 max_size, double max_age)
Typedef Documentation
jlogger_sink_filter
typedef bool jlogger_sink_filter(jlogger_sink_t self, jlog_level level, const char *fmt, va_list args)
Definition at line 30 of file jlog.h.
jlogger_sink_fn
typedef bool jlogger_sink_fn(jlogger_sink_t self, jlog_level level, const char *fmt,...)
Definition at line 29 of file jlog.h.
jlogger_sink_free_fn
typedef void jlogger_sink_free_fn(jlogger_sink_t self)
Definition at line 28 of file jlog.h.
jlogger_sink_t
typedef jlogger_sink_s* jlogger_sink_t
Definition at line 27 of file jlog.h.
jlogger_t
typedef jlogger_s* jlogger_t
Definition at line 23 of file jlog.h.
Enumeration Type Documentation
jlog_level
enum jlog_level
Enumerator
JLOG_LEVEL_TRACE
JLOG_LEVEL_DEBUG
JLOG_LEVEL_INFO
JLOG_LEVEL_WARN
JLOG_LEVEL_ERROR
JLOG_LEVEL_FATAL
Definition at line 7 of file jlog.h.
Function Documentation
jlog_level_to_string()
const char* jlog_level_to_string (jlog_level level)
Definition at line 8 of file jlog.c.
References JLOG_LEVEL_DEBUG, JLOG_LEVEL_ERROR, JLOG_LEVEL_FATAL, JLOG_LEVEL_INFO, JLOG_LEVEL_TRACE, and JLOG_LEVEL_WARN.
Referenced by jlogger_log_level_impl().
jlogger_add_sink()
void jlogger_add_sink (jlogger_t self, jlogger_sink_t sink)
Definition at line 45 of file jlog.c.
References Vector_push_back().
jlogger_file_sink_new()
void jlogger_file_sink_new (jlogger_sink_t sink, char * path)
Create a new file sink.
Parameters
sink The sink to initialise.
path A path to the file to log to. Ownership is transferred to the sink.
Definition at line 174 of file jlog.c.
References jlogger_file_sink(), jlogger_file_sink_free(), and Vector_default().
jlogger_free()
void jlogger_free (jlogger_t self)
Definition at line 36 of file jlog.c.
References Vector_dest().
jlogger_log()
bool jlogger_log (jlogger_t self, jlog_level level, const char * fmt, ...)
Definition at line 63 of file jlog.c.
References jlogger_vlog().
jlogger_log_debug()
bool jlogger_log_debug (jlogger_t self, const char * fmt, ...)
jlogger_log_error()
bool jlogger_log_error (jlogger_t self, const char * fmt, ...)
jlogger_log_fatal()
bool jlogger_log_fatal (jlogger_t self, const char * fmt, ...)
jlogger_log_info()
bool jlogger_log_info (jlogger_t self, const char * fmt, ...)
jlogger_log_trace()
bool jlogger_log_trace (jlogger_t self, const char * fmt, ...)
jlogger_log_warn()
bool jlogger_log_warn (jlogger_t self, const char * fmt, ...)
jlogger_new()
jlogger_t jlogger_new ()
Definition at line 27 of file jlog.c.
References Vector_init().
jlogger_rotating_file_sink_new()
void jlogger_rotating_file_sink_new (jlogger_sink_t sink, char * path_template, uptr path_template_len, u32 max_size, double max_age)
Definition at line 302 of file jlog.c.
References jlogger_rotating_file_sink(), jloggger_rotating_file_sink_free(), and Vector_default().
jlogger_sink_add_filter()
void jlogger_sink_add_filter (jlogger_sink_t self, jlogger_sink_filter * filter)
Definition at line 145 of file jlog.c.
References filter, and Vector_push_back().
jlogger_std_hybrid_sink_new()
void jlogger_std_hybrid_sink_new (jlogger_sink_t sink)
Definition at line 140 of file jlog.c.
References jlogger_std_hybrid_sink(), and Vector_default().
jlogger_stderr_sink_new()
void jlogger_stderr_sink_new (jlogger_sink_t sink)
Definition at line 125 of file jlog.c.
References jlogger_stderr_sink(), and Vector_default().
jlogger_stdout_sink_new()
void jlogger_stdout_sink_new (jlogger_sink_t sink)
Definition at line 112 of file jlog.c.
References jlogger_stdout_sink(), and Vector_default().