JC: jvector.h File Reference
jvector.h File Reference
Dynamic array that resizes itself as necessary.
#include <stdarg.h>
#include <stdbool.h>
#include "jint.h"
Data Structures
struct Vector
struct Vector_minmax
Typedefs
typedef void * vector_mapping_t(const void *,...)
typedef bool vector_filter_t(const void *,...)
typedef const void * vector_reduce_t(const void *, const void *,...)
typedef const void * vector_fold_t(const void *, const void *,...)
typedef int vector_compare_t(const void *, const void *,...)
Functions
iptr Vector_default (Vector *vec)
Create a Vector with sensible defaults.
iptr Vector_init (Vector *vec)
Initialise a Vector with a given capacity and growth_factor.
iptr Vector_with_capacity (Vector *vec, uptr capacity)
Initialise a Vector with a given capacity.
void Vector_dest (Vector *vec)
Finalise a Vector.
iptr Vector_new (Vector *vec, uptr count, void *elt,...)
Create a new Vector from the given values.
iptr Vector_from (Vector *vec, uptr count, void **elts)
Create a Vector from an array of values.
iptr Vector_grow (Vector *vec)
Grow a Vector.
iptr Vector_grow_if_full (Vector *vec)
Grow a Vector if it has no free space.
iptr Vector_push_back (Vector *vec, void *elt)
Append (push) and element to the Vector.
void Vector_pop_back (Vector *vec, void **out)
Remove the last element of the Vector and put it into out.
iptr Vector_append_many (Vector *vec, uptr count, void *elt,...)
Append many elements to a Vector at once.
iptr Vector_append_arr (Vector *vec, uptr count, void **elts)
Append an array to a Vector.
iptr Vector_reserve (Vector *vec, uptr capacity)
Reserve at least capacity elements of space for a Vector.
iptr Vector_reserve_exact (Vector *vec, uptr capacity)
Reserve exactly capacity elements of space for a Vector.
iptr Vector_shrink_to_fit (Vector *vec)
Shrink a Vector to fit exactly its elements.
void Vector_map (Vector *vec, vector_mapping_t mapping,...)
Map a function over a Vector.
void Vector_filter (Vector *vec, vector_filter_t predicate,...)
Filter a Vector by removing elements for which the predicate returns false.
const void * Vector_reduce (Vector *vec, vector_reduce_t reduce,...)
Apply a function to each element of a Vector, threading an accumulator value through.
const void * Vector_fold (Vector *vec, vector_fold_t fold, const void *initial,...)
Apply a function to each element of a Vector, threading an accumulator value through.
const void * Vector_max (Vector *vec, vector_compare_t compare,...)
Find the maximum element of a Vector.
const void * Vector_min (Vector *vec, vector_compare_t compare,...)
Find the minimum element of a Vector.
struct Vector_minmax Vector_minmax (Vector *vec, vector_compare_t compare,...)
Detailed Description
Dynamic array that resizes itself as necessary.
Definition in file jvector.h.
Typedef Documentation
vector_compare_t
typedef int vector_compare_t(const void *, const void *,...)
Definition at line 26 of file jvector.h.
vector_filter_t
typedef bool vector_filter_t(const void *,...)
Definition at line 23 of file jvector.h.
vector_fold_t
typedef const void* vector_fold_t(const void *, const void *,...)
Definition at line 25 of file jvector.h.
vector_mapping_t
typedef void* vector_mapping_t(const void *,...)
Definition at line 22 of file jvector.h.
vector_reduce_t
typedef const void* vector_reduce_t(const void *, const void *,...)
Definition at line 24 of file jvector.h.
Function Documentation
Vector_append_arr()
iptr Vector_append_arr (Vector * vec, uptr count, void ** elts)
Append an array to a Vector.
Remarks
This function performs at most one allocation.
The elements of elts are copied to the Vector's buffer.
Parameters
vec The Vector to append to.
count The number of elements to append.
elts The array of values to append.
Returns
On success, 0. On error, -1 and errno is set to indicate the error.
Definition at line 163 of file jvector.c.
References Vector::data, Vector::length, and Vector_reserve().
Vector_append_many()
iptr Vector_append_many (Vector * vec, uptr count, void * elt, ...)
Append many elements to a Vector at once.
Remarks
This function performs at most one allocation.
Parameters
vec The Vector to append to.
count The number of elements to append.
elt The elements to append.
...
Returns
On success, 0. On error, -1 and errno is set to indicate the error.
Definition at line 144 of file jvector.c.
References Vector::data, Vector::length, and Vector_reserve().
Vector_default()
iptr Vector_default (Vector * vec)
Create a Vector with sensible defaults.
Remarks
capacity is set to 8 and growth_factor is set to 2.
Parameters
vec The Vector to initialise.
Returns
On success, 0. On error, -1 and errno is set to indicate the error.
Definition at line 13 of file jvector.c.
References Vector::capacity, Vector::growth_factor, Vector::length, and Vector_init().
Referenced by jiterator_collect(), jlogger_file_sink_new(), jlogger_rotating_file_sink_new(), jlogger_std_hybrid_sink_new(), jlogger_stderr_sink_new(), and jlogger_stdout_sink_new().
Vector_dest()
void Vector_dest (Vector * vec)
Finalise a Vector.
Frees allocated memory and resets capacity, growth_factor, and factor to 0.
Parameters
vec The Vector to finalise.
Definition at line 48 of file jvector.c.
References Vector::capacity, Vector::data, Vector::growth_factor, and Vector::length.
Referenced by jlogger_free().
Vector_filter()
void Vector_filter (Vector * vec, vector_filter_t predicate, ...)
Filter a Vector by removing elements for which the predicate returns false.
Remarks
The predicate is called for each element in the Vector, in reverse order.
Parameters
vec The Vector to predicate.
predicate The predicate to call for each element.
... Extra arguments to pass to predicate.
Definition at line 239 of file jvector.c.
References Vector::data, and Vector::length.
Vector_fold()
const void* Vector_fold (Vector * vec, vector_fold_t fold, const void * initial, ...)
Apply a function to each element of a Vector, threading an accumulator value through.
Apply the function to the initial value and the first element of the vector. Then feed the result of the first application into the second application, and so on.
Parameters
vec The Vector to apply the function to.
fold The function to apply to each element.
initial The initial value to thread through.
... Extra arguments to pass to fold.
Returns
The final value of the accumulator.
Definition at line 283 of file jvector.c.
References Vector::data, fold, and Vector::length.
Vector_from()
iptr Vector_from (Vector * vec, uptr count, void ** elts)
Create a Vector from an array of values.
Parameters
vec The Vector to initialise.
count The number of elements in the array.
elts The array of elements.
Remarks
The values of elts are copied to the Vector's buffer.
Returns
On success, 0. On error, -1 and errno is set to indicate the error.
Definition at line 80 of file jvector.c.
References Vector::capacity, Vector::data, Vector::growth_factor, Vector::length, and Vector_init().
Vector_grow()
iptr Vector_grow (Vector * vec)
Grow a Vector.
Remarks
This multiplies capacity by growth_factor and then allocates new memory for the Vector's buffer.
Values past length are set to 0.
Parameters
vec The Vector to grow.
Returns
On success, 0. On error, -1 and errno is set to indicate the error.
Definition at line 94 of file jvector.c.
References Vector::capacity, Vector::data, Vector::growth_factor, and Vector::length.
Referenced by Vector_grow_if_full().
Vector_grow_if_full()
iptr Vector_grow_if_full (Vector * vec)
Grow a Vector if it has no free space.
Parameters
vec The Vector to grow.
Returns
On success, 0. On error, -1 and errno is set to indicate the error.
Definition at line 108 of file jvector.c.
References Vector::capacity, Vector::length, and Vector_grow().
Referenced by jiterator_collect(), and Vector_push_back().
Vector_init()
iptr Vector_init (Vector * vec)
Initialise a Vector with a given capacity and growth_factor.
Parameters
vec The Vector to initialise.
Returns
On success, 0. On error, -1 and errno is set to indicate the error.
Definition at line 23 of file jvector.c.
References Vector::capacity, Vector::data, Vector::growth_factor, and Vector::length.
Referenced by jlogger_new(), Vector_default(), Vector_from(), and Vector_with_capacity().
Vector_map()
void Vector_map (Vector * vec, vector_mapping_t mapping, ...)
Map a function over a Vector.
Remarks
The function is called for each element in the Vector, in order.
Parameters
vec The Vector to map over.
mapping The function to call for each element.
... Extra arguments to pass to mapping.
Definition at line 225 of file jvector.c.
References Vector::data, and Vector::length.
Vector_max()
const void* Vector_max (Vector * vec, vector_compare_t compare, ...)
Find the maximum element of a Vector.
Parameters
vec The Vector to find the maximum element of.
compare The function to compare elements.
Remarks
compare should return a negative value if the first argument is less than the second, a positive value if the first argument is greater than the second, and 0 if the arguments are equal.
If two elements are equal, the first one is retained.
Returns
The maximum element of vec.
Definition at line 329 of file jvector.c.
References keep_greater(), max, and Vector_reduce().
Vector_min()
const void* Vector_min (Vector * vec, vector_compare_t compare, ...)
Find the minimum element of a Vector.
Parameters
vec The Vector to find the minimum element of.
compare The function to compare elements.
Remarks
compare should return a negative value if the first argument is less than the second, a positive value if the first argument is greater than the second, and 0 if the arguments are equal.
If two elements are equal, the first one is retained.
Returns
The minimum element of vec.
Definition at line 344 of file jvector.c.
References keep_lesser(), min, and Vector_reduce().
Vector_minmax()
struct Vector_minmax Vector_minmax (Vector * vec, vector_compare_t compare, ...)
Definition at line 344 of file jvector.c.
Vector_new()
iptr Vector_new (Vector * vec, uptr count, void * elt, ...)
Create a new Vector from the given values.
Parameters
vec The Vector to initialise.
count The initial number of elements
elt The elements to put in the new Vector.
...
Returns
On success, 0. On error, -1 and errno is set to indicate the error.
Definition at line 61 of file jvector.c.
References Vector::data, Vector::length, and Vector_with_capacity().
Vector_pop_back()
void Vector_pop_back (Vector * vec, void ** out)
Remove the last element of the Vector and put it into out.
Parameters
vec The Vector to pop the last element from.
out Pointer to where to put the last element.
Definition at line 131 of file jvector.c.
References Vector::data, and Vector::length.
Vector_push_back()
iptr Vector_push_back (Vector * vec, void * elt)
Append (push) and element to the Vector.
Remarks
This function grows the Vector if necessary.
Parameters
vec The Vector to append to.
elt The value to append.
Returns
On success, 0. On error, -1 and errno is set to indicate the error.
Definition at line 120 of file jvector.c.
References Vector::data, Vector::length, and Vector_grow_if_full().
Referenced by jlogger_add_sink(), and jlogger_sink_add_filter().
Vector_reduce()
const void* Vector_reduce (Vector * vec, vector_reduce_t reduce, ...)
Apply a function to each element of a Vector, threading an accumulator value through.
Apply the function to the first two elements of the vector. Then feed the result of the first application into the second application, and so on.
Parameters
vec The Vector to apply the function to.
reduce The function to apply to each element.
... Extra arguments to pass to reduce.
Returns
The final value of the accumulator.
Definition at line 263 of file jvector.c.
References Vector::data, Vector::length, and reduce.
Referenced by Vector_max(), and Vector_min().
Vector_reserve()
iptr Vector_reserve (Vector * vec, uptr capacity)
Reserve at least capacity elements of space for a Vector.
Remarks
Only one allocation is made.
If capacity is the same as the Vector's capacity, no allocation is made.
capacity must be greater than the Vector's current capacity.
Parameters
vec The Vector to reserve space in.
capacity The minimum total amount of space to be reserved.
Returns
On success, 0. On error, -1 and errno is set to indicate the error.
Definition at line 177 of file jvector.c.
References Vector::capacity, Vector::data, Vector::growth_factor, and Vector::length.
Referenced by Vector_append_arr(), and Vector_append_many().
Vector_reserve_exact()
iptr Vector_reserve_exact (Vector * vec, uptr capacity)
Reserve exactly capacity elements of space for a Vector.
Remarks
Only one allocation is made.
If capacity is the same as the Vector's capacity, no allocation is made.
capacity must be greater than the Vector's current capacity.
Parameters
vec The Vector to reserve space in.
capacity The total amount of space to be reserved.
Returns
On success, 0. On error, -1 and errno is set to indicate the error.
Definition at line 199 of file jvector.c.
References Vector::capacity, and Vector::data.
Vector_shrink_to_fit()
iptr Vector_shrink_to_fit (Vector * vec)
Shrink a Vector to fit exactly its elements.
Parameters
vec The Vector to shrink.
Returns
On success, 0. On error, -1 and errno is set to indicate the error.
Definition at line 212 of file jvector.c.
References Vector::capacity, Vector::data, and Vector::length.
Vector_with_capacity()
iptr Vector_with_capacity (Vector * vec, uptr capacity)
Initialise a Vector with a given capacity.
Remarks
growth_factor is set to 2.
Parameters
vec The Vector to initialise.
capacity The initial capacity of vec.
Returns
On success, 0. On error, -1 and errno is set to indicate the error.
Definition at line 39 of file jvector.c.
References Vector::capacity, Vector::growth_factor, and Vector_init().
Referenced by Vector_new().