JC: jvector.c File Reference
jvector.c File Reference
#include <assert.h>
#include <stdlib.h>
#include <memory.h>
#include "jvector.h"
Functions
iptr Vector_default (Vector *vec)
Create a Vector with sensible defaults.
iptr Vector_init (Vector *vec)
Initialise a Vector with a given capacity and growth_factor.
iptr Vector_with_capacity (Vector *vec, uptr capacity)
Initialise a Vector with a given capacity.
void Vector_dest (Vector *vec)
Finalise a Vector.
iptr Vector_new (Vector *vec, uptr count, void *elt,...)
Create a new Vector from the given values.
iptr Vector_from (Vector *vec, uptr count, void **elts)
Create a Vector from an array of values.
iptr Vector_grow (Vector *vec)
Grow a Vector.
iptr Vector_grow_if_full (Vector *vec)
Grow a Vector if it has no free space.
iptr Vector_push_back (Vector *vec, void *elt)
Append (push) and element to the Vector.
void Vector_pop_back (Vector *vec, void **out)
Remove the last element of the Vector and put it into out.
iptr Vector_append_many (Vector *vec, uptr count, void *elt,...)
Append many elements to a Vector at once.
iptr Vector_append_arr (Vector *vec, uptr count, void **elts)
Append an array to a Vector.
iptr Vector_reserve (Vector *vec, uptr capacity)
Reserve at least capacity elements of space for a Vector.
iptr Vector_reserve_exact (Vector *vec, uptr capacity)
Reserve exactly capacity elements of space for a Vector.
iptr Vector_shrink_to_fit (Vector *vec)
Shrink a Vector to fit exactly its elements.
Function Documentation
Vector_append_arr()
iptr Vector_append_arr (Vector * vec, uptr count, void ** elts)
Append an array to a Vector.
Remarks
This function performs at most one allocation.
The elements of elts are copied to the Vector's buffer.
Parameters
vec The Vector to append to.
count The number of elements to append.
elts The array of values to append.
Returns
On success, 0. On error, -1 and errno is set to indicate the error.
Definition at line 161 of file jvector.c.
References Vector::data, Vector::length, and Vector_reserve().
Vector_append_many()
iptr Vector_append_many (Vector * vec, uptr count, void * elt, ...)
Append many elements to a Vector at once.
Remarks
This function performs at most one allocation.
Parameters
vec The Vector to append to.
count The number of elements to append.
elt The elements to append.
...
Returns
On success, 0. On error, -1 and errno is set to indicate the error.
Definition at line 142 of file jvector.c.
References Vector::data, Vector::length, and Vector_reserve().
Vector_default()
iptr Vector_default (Vector * vec)
Create a Vector with sensible defaults.
Remarks
capacity is set to 8 and growth_factor is set to 2.
Parameters
vec The Vector to initialise.
Returns
On success, 0. On error, -1 and errno is set to indicate the error.
Definition at line 10 of file jvector.c.
References Vector::capacity, Vector::growth_factor, Vector::length, and Vector_init().
Vector_dest()
void Vector_dest (Vector * vec)
Finalise a Vector.
Frees allocated memory and resets capacity, growth_factor, and factor to 0.
Parameters
vec The Vector to finalise.
Definition at line 45 of file jvector.c.
References Vector::capacity, Vector::data, Vector::growth_factor, and Vector::length.
Vector_from()
iptr Vector_from (Vector * vec, uptr count, void ** elts)
Create a Vector from an array of values.
Parameters
vec The Vector to initialise.
count The number of elements in the array.
elts The array of elements.
Remarks
The values of elts are copied to the Vector's buffer.
Returns
On success, 0. On error, -1 and errno is set to indicate the error.
Definition at line 77 of file jvector.c.
References Vector::capacity, Vector::data, Vector::growth_factor, Vector::length, and Vector_init().
Vector_grow()
iptr Vector_grow (Vector * vec)
Grow a Vector.
Remarks
This multiplies capacity by growth_factor and then allocates new memory for the Vector's buffer.
Values past length are set to 0.
Parameters
vec The Vector to grow.
Returns
On success, 0. On error, -1 and errno is set to indicate the error.
Definition at line 91 of file jvector.c.
References Vector::capacity, Vector::data, Vector::growth_factor, and Vector::length.
Referenced by Vector_grow_if_full().
Vector_grow_if_full()
iptr Vector_grow_if_full (Vector * vec)
Grow a Vector if it has no free space.
Parameters
vec The Vector to grow.
Returns
On success, 0. On error, -1 and errno is set to indicate the error.
Definition at line 106 of file jvector.c.
References Vector::capacity, Vector::length, and Vector_grow().
Referenced by Vector_push_back().
Vector_init()
iptr Vector_init (Vector * vec)
Initialise a Vector with a given capacity and growth_factor.
Parameters
vec The Vector to initialise.
Returns
On success, 0. On error, -1 and errno is set to indicate the error.
Definition at line 20 of file jvector.c.
References Vector::capacity, Vector::data, Vector::growth_factor, and Vector::length.
Referenced by Vector_default(), Vector_from(), and Vector_with_capacity().
Vector_new()
iptr Vector_new (Vector * vec, uptr count, void * elt, ...)
Create a new Vector from the given values.
Parameters
vec The Vector to initialise.
count The initial number of elements
elt The elements to put in the new Vector.
...
Returns
On success, 0. On error, -1 and errno is set to indicate the error.
Definition at line 58 of file jvector.c.
References Vector::data, Vector::length, and Vector_with_capacity().
Vector_pop_back()
void Vector_pop_back (Vector * vec, void ** out)
Remove the last element of the Vector and put it into out.
Parameters
vec The Vector to pop the last element from.
out Pointer to where to put the last element.
Definition at line 129 of file jvector.c.
References Vector::data, and Vector::length.
Vector_push_back()
iptr Vector_push_back (Vector * vec, void * elt)
Append (push) and element to the Vector.
Remarks
This function grows the Vector if necessary.
Parameters
vec The Vector to append to.
elt The value to append.
Returns
On success, 0. On error, -1 and errno is set to indicate the error.
Definition at line 118 of file jvector.c.
References Vector::data, Vector::length, and Vector_grow_if_full().
Vector_reserve()
iptr Vector_reserve (Vector * vec, uptr capacity)
Reserve at least capacity elements of space for a Vector.
Remarks
Only one allocation is made.
If capacity is the same as the Vector's capacity, no allocation is made.
capacity must be greater than the Vector's current capacity.
Parameters
vec The Vector to reserve space in.
capacity The minimum total amount of space to be reserved.
Returns
On success, 0. On error, -1 and errno is set to indicate the error.
Definition at line 175 of file jvector.c.
References Vector::capacity, Vector::data, Vector::growth_factor, and Vector::length.
Referenced by Vector_append_arr(), and Vector_append_many().
Vector_reserve_exact()
iptr Vector_reserve_exact (Vector * vec, uptr capacity)
Reserve exactly capacity elements of space for a Vector.
Remarks
Only one allocation is made.
If capacity is the same as the Vector's capacity, no allocation is made.
capacity must be greater than the Vector's current capacity.
Parameters
vec The Vector to reserve space in.
capacity The total amount of space to be reserved.
Returns
On success, 0. On error, -1 and errno is set to indicate the error.
Definition at line 198 of file jvector.c.
References Vector::capacity, and Vector::data.
Vector_shrink_to_fit()
iptr Vector_shrink_to_fit (Vector * vec)
Shrink a Vector to fit exactly its elements.
Parameters
vec The Vector to shrink.
Returns
On success, 0. On error, -1 and errno is set to indicate the error.
Definition at line 212 of file jvector.c.
References Vector::capacity, Vector::data, and Vector::length.
Vector_with_capacity()
iptr Vector_with_capacity (Vector * vec, uptr capacity)
Initialise a Vector with a given capacity.
Remarks
growth_factor is set to 2.
Parameters
vec The Vector to initialise.
capacity The initial capacity of vec.
Returns
On success, 0. On error, -1 and errno is set to indicate the error.
Definition at line 36 of file jvector.c.
References Vector::capacity, Vector::growth_factor, and Vector_init().
Referenced by Vector_new().